### ISSUE TITLE
Nonexistent Boost config macro BOOST_NO_CXX11_HDR_MEMORY

### ISSUE THREAD

**Issue by jefftrull** [boostorg/container_hash#10]
An automated search for erroneous macro usage picked this up here and in Wave. There is no such macro because `<memory>` predates C++11, so the test in `extensions.hpp` is always true.

**Comment by mclow** [comment]
Created https://github.com/boostorg/container_hash/pull/11 to address this.

**Comment by jefftrull** [comment]
Looks like this was resolved.
