### ISSUE TITLE
Missing hash_value overloads for C++11 and later containers

### ISSUE THREAD

**Issue by zamazan4ik** [boostorg/container_hash#3]
Hello.

In Boost.ContainerHash library there are no `hash_value` overloads for all containers with PMR allocator. Also overloads for unordered_(multi)set/map are missing.

Do you plan to add it later?

**Comment by pdimov** [comment]
These should all be supported now (on develop).

**Comment by pdimov** [comment]
The develop branch has been merged now, so this should be resolved.
