### ISSUE TITLE
boost::hash needs c++20 to compile with clang 15 and gcc 10

### ISSUE THREAD

**Issue by martinsjogren** [boostorg/container_hash#36]
I have a blob type with begin/end member functions that return const void* and when I try to use that with boost::unordered_map I get a compilation error with gcc 10 and clang 15 unless I compile with -std=c++20 (funny enough it works with gcc 11+ and msvc)

Am I doing something strange or are the ADL changes in c++20 relevant for this case? I attached a small repro as well as the output from compiling with gcc-10 -std=c++17 and clang-15 -std=c++17

Either way it feels like boost shouldn't require c++20 to compile this example where I provide my own hash_value function, right? I'm really confused whether this is a bug in boost or a bug somewhere in gcc/clang or if my code is doing something wrong.

[hash_repro.tar.gz](https://github.com/boostorg/container_hash/files/14493465/hash_repro.tar.gz)

**Comment by pdimov** [comment]
Should be fixed for 1.85. The beta will be going out in a few days.

**Comment by martinsjogren** [comment]
Super, and thank you for the workaround!
